name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest
        pip install pytest-cov
        
    - name: Install xmlstarlet
      run: brew install xmlstarlet
        
    - name: Run tests & get current coverage
      run: |
        pytest --cov=src --cov-report xml:current.xml

    - name: Extract previous commit coverage
      run: |
          git checkout HEAD^
          pytest --cov=src --cov-report xml:previous.xml
          git checkout -
          
    - name: Compare coverage
      run: |
          current_coverage=$(xml sel -t -v "/coverage/@line-rate" current.xml)
          previous_coverage=$(xml sel -t -v "/coverage/@line-rate" previous.xml)
          
          echo "Current coverage: $current_coverage"
          echo "Previous coverage: $previous_coverage"
          
          if (( $(echo "$current_coverage < $previous_coverage" | bc -l) )); then
            echo "Code coverage decreased from previous commit."
            exit 1
          fi

    - name: Display coverage report and test results
      uses: actions/github-script@v5
      with:
        github-token: ${{ github.token }}
        script: |
          const fs = require('fs');

          const coverageReport = fs.readFileSync('current.xml', 'utf8');
    
          const octokit = github.getOctokit(core.getInput('github-token'));

    
          octokit.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `
              #### Coverage Report
              \`\`\`
              ${coverageReport}
              \`\`\`
            `
          });


