name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest
        pip install pytest-cov

        
    - name: Run tests with coverage
      run: |
        pytest --cov=src

    - name: Extract previous commit coverage
      run: |
          git checkout HEAD^
          pytest --cov=my_package tests/ --cov-report xml:cov.xml
          git checkout -

          
    - name: Compare coverage
      run: |
          current_coverage=$(xml sel -t -v "/coverage/@line-rate" cov.xml)
          previous_coverage=$(xml sel -t -v "/coverage/@line-rate" cov.xml)
          if (( $(echo "$current_coverage < $previous_coverage" | bc -l) )); then
            echo "Code coverage decreased from previous commit."
            exit 1

